### ISSUE TITLE
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by zuoweic** [hkchengrex/Tracking-Anything-with-DEVA#118]
I ran python demo/demo_with_text.py --chunk_size 4 --img_path ./example/vipseg/images/12_1mWNahzcsAc --amp --temporal_setting semionline --size 480 --output ./example/output --prompt person.hat.horse 

But i got some error:

(deva2) y@Station:~/4tdisk/DEVA/Tracking-Anything-with-DEVA$ python demo/demo_with_text.py --chunk_size 4 --img_path ./example/vipseg/images/12_1mWNahzcsAc --amp --temporal_setting semionline --size 480 --output ./example/output --prompt person.hat.horse 
UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /opt/conda/conda-bld/pytorch_1682343967769/work/aten/src/ATen/native/TensorShape.cpp:3483.)
final text_encoder_type: bert-base-uncased
FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.seq_relationship.bias', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Traceback (most recent call last):
  File "/home/y/4tdisk/DEVA/Tracking-Anything-with-DEVA/demo/demo_with_text.py", line 35, in <module>
    gd_model, sam_model = get_grounding_dino_model(cfg, 'cuda')
  File "/home/y/4tdisk/DEVA/Tracking-Anything-with-DEVA/deva/ext/grounding_dino.py", line 29, in get_grounding_dino_model
    gd_model = GroundingDINOModel(model_config_path=GROUNDING_DINO_CONFIG_PATH,
  File "/home/y/4tdisk/DEVA/Tracking-Anything-with-DEVA/Grounded-Segment-Anything/GroundingDINO/groundingdino/util/inference.py", line 119, in __init__
    self.model = load_model(
  File "/home/y/4tdisk/DEVA/Tracking-Anything-with-DEVA/Grounded-Segment-Anything/GroundingDINO/groundingdino/util/inference.py", line 33, in load_model
    checkpoint = torch.load(model_checkpoint_path, map_location="cpu")
  File "/home/y/anaconda3/envs/deva2/lib/python3.10/site-packages/torch/serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/home/y/anaconda3/envs/deva2/lib/python3.10/site-packages/torch/serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

I do not know why, could help me? Thank you very much!

**Comment by zuoweic** [comment]
I download the models again and it works now, thanks
