### ISSUE TITLE
Running examples does not work

### ISSUE THREAD

**Issue by nasserdr** [hkchengrex/Tracking-Anything-with-DEVA#12]
Running these two examples give errors:

```
~/Tracking-Anything-with-DEVA$ python demo/demo_with_text.py --chunk_size 4 --img_path ./example/vipseg/images/12_1mWNahzcsAc --amp --temporal_setting semionline --size 480  --output ./example/output --prompt person.hat.horse
Traceback (most recent call last):
  File "~/Tracking-Anything-with-DEVA/deva/ext/grounding_dino.py", line 12, in <module>
    from groundingdino.util.inference import Model as GroundingDINOModel
ModuleNotFoundError: No module named 'groundingdino'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo/demo_with_text.py", line 15, in <module>
    from deva.ext.grounding_dino import get_grounding_dino_model
  File "~Tracking-Anything-with-DEVA/deva/ext/grounding_dino.py", line 15, in <module>
    from GroundingDINO.groundingdino.util.inference import Model as GroundingDINOModel
ModuleNotFoundError: No module named 'GroundingDINO'
```

**Comment by hkchengrex** [comment]
Similar to #9  -- did you install Grounded-SAM?
