### ISSUE TITLE
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1293) of binary

### ISSUE THREAD

**Issue by Tensorrrrrr** [hkchengrex/Tracking-Anything-with-DEVA#21]
When I use: python -m torch.distributed.run --nproc_per_node=2 deva/train.py --exp_id deva_retrain --stage 0

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1293) of binary: /root/miniconda3/envs/deva/bin/python
Traceback (most recent call last):
  File "/root/miniconda3/envs/deva/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/envs/deva/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/miniconda3/envs/deva/lib/python3.8/site-packages/torch/distributed/run.py", line 798, in <module>
    main()
  File "/root/miniconda3/envs/deva/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/root/miniconda3/envs/deva/lib/python3.8/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/root/miniconda3/envs/deva/lib/python3.8/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/root/miniconda3/envs/deva/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/miniconda3/envs/deva/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
deva/train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-09-21_10:43:21
  host      : autodl-container-b8cd11b052-2057d9be
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1293)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

My GPUs are 2080Ti, how can I solve the problem, thanks

**Comment by hkchengrex** [comment]
Doesn't look like the full error message to me. Can you post more?

**Comment by Tensorrrrrr** [comment]
> CUDA Device count: 2
Rank 0 of 2 initialized.
We are using 2 GPUs.
We are now starting to train stage 0
Logging is enabled for rank 0
CUDA Device count: 2
Rank 1 of 2 initialized.
We are using 2 GPUs.
We are now starting to train stage 0
Traceback (most recent call last):
  File "deva/train.py", line 78, in <module>
    logger = TensorboardLogger(config['exp_id'], long_id)
  File "/root/autodl-tmp/Tracking-Anything-with-DEVA-main/deva/utils/logger.py", line 49, in __init__
    repo = git.Repo(".")
  File "/root/miniconda3/envs/deva/lib/python3.8/site-packages/git/repo/base.py", line 266, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: /root/autodl-tmp/Tracking-Anything-with-DEVA-main
Downloading: "https://download.pytorch.org/models/resnet18-5c106cde.pth" to /root/.cache/torch/hub/checkpoints/resnet18-5c106cde.pth
  0%|▎                                                                                                                      | 128k/44.7M [00:00<03:25, 227kB/s]WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1294 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1293) of binary: /root/miniconda3/envs/deva/bin/python
Traceback (most recent call last):
  File "/root/miniconda3/envs/deva/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/envs/deva/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/miniconda3/envs/deva/lib/python3.8/site-packages/torch/distributed/run.py", line 798, in <module>
    main()
  File "/root/miniconda3/envs/deva/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/root/miniconda3/envs/deva/lib/python3.8/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/root/miniconda3/envs/deva/lib/python3.8/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/root/miniconda3/envs/deva/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/miniconda3/envs/deva/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
deva/train.py FAILED
------------------------------------------------------------

**Comment by hkchengrex** [comment]
You probably didn't clone the repository but downloaded it as a zip instead.

**Comment by Tensorrrrrr** [comment]
Cheers！
