### ISSUE TITLE
Problem installing Grounded-Segment-Anything with Cuda 12.2

### ISSUE THREAD

**Issue by AK51** [hkchengrex/Tracking-Anything-with-DEVA#24]
Hi,

I was trying your Tracking-Anything-with-DEVA, but when I install the GroundingDINO, it said
```
        The detected CUDA version (12.2) mismatches the version that was used to compile
        PyTorch (11.8). Please make sure to use the same CUDA versions.
        
        [end of output]
```
May I know how I can solve it? Thx

Below is the full log. Thx

```
python -m pip install -e GroundingDINO
Obtaining file:///media/ak/HD/DEVA/Grounded-Segment-Anything/Grounded-Segment-Anything/GroundingDINO
  Preparing metadata (setup.py) ... done
Requirement already satisfied: torch in /home/ak/anaconda3/lib/python3.9/site-packages (from groundingdino==0.1.0) (2.0.1+cu118)
Requirement already satisfied: torchvision in /home/ak/anaconda3/lib/python3.9/site-packages (from groundingdino==0.1.0) (0.15.2+cu118)
Requirement already satisfied: transformers in /home/ak/anaconda3/lib/python3.9/site-packages (from groundingdino==0.1.0) (4.30.2)
Requirement already satisfied: addict in /home/ak/anaconda3/lib/python3.9/site-packages (from groundingdino==0.1.0) (2.4.0)
Requirement already satisfied: yapf in /home/ak/anaconda3/lib/python3.9/site-packages (from groundingdino==0.1.0) (0.31.0)
Requirement already satisfied: timm in /home/ak/anaconda3/lib/python3.9/site-packages (from groundingdino==0.1.0) (0.9.2)
Requirement already satisfied: numpy in /home/ak/anaconda3/lib/python3.9/site-packages (from groundingdino==0.1.0) (1.23.5)
Requirement already satisfied: opencv-python in /home/ak/anaconda3/lib/python3.9/site-packages (from groundingdino==0.1.0) (4.7.0.68)
Requirement already satisfied: supervision in /home/ak/anaconda3/lib/python3.9/site-packages (from groundingdino==0.1.0) (0.6.0)
Requirement already satisfied: pycocotools in /home/ak/anaconda3/lib/python3.9/site-packages (from groundingdino==0.1.0) (2.0.7)
Requirement already satisfied: matplotlib>=2.1.0 in /home/ak/anaconda3/lib/python3.9/site-packages (from pycocotools->groundingdino==0.1.0) (3.8.0)
Requirement already satisfied: pyyaml in /home/ak/anaconda3/lib/python3.9/site-packages (from timm->groundingdino==0.1.0) (6.0)
Requirement already satisfied: huggingface-hub in /home/ak/anaconda3/lib/python3.9/site-packages (from timm->groundingdino==0.1.0) (0.15.1)
Requirement already satisfied: safetensors in /home/ak/anaconda3/lib/python3.9/site-packages (from timm->groundingdino==0.1.0) (0.3.1)
Requirement already satisfied: filelock in /home/ak/anaconda3/lib/python3.9/site-packages (from torch->groundingdino==0.1.0) (3.6.0)
Requirement already satisfied: typing-extensions in /home/ak/anaconda3/lib/python3.9/site-packages (from torch->groundingdino==0.1.0) (4.7.0)
Requirement already satisfied: sympy in /home/ak/anaconda3/lib/python3.9/site-packages (from torch->groundingdino==0.1.0) (1.10.1)
Requirement already satisfied: networkx in /home/ak/anaconda3/lib/python3.9/site-packages (from torch->groundingdino==0.1.0) (3.1)
Requirement already satisfied: jinja2 in /home/ak/anaconda3/lib/python3.9/site-packages (from torch->groundingdino==0.1.0) (2.11.3)
Requirement already satisfied: triton==2.0.0 in /home/ak/anaconda3/lib/python3.9/site-packages (from torch->groundingdino==0.1.0) (2.0.0)
Requirement already satisfied: cmake in /home/ak/anaconda3/lib/python3.9/site-packages (from triton==2.0.0->torch->groundingdino==0.1.0) (3.25.0)
Requirement already satisfied: lit in /home/ak/anaconda3/lib/python3.9/site-packages (from triton==2.0.0->torch->groundingdino==0.1.0) (15.0.7)
Requirement already satisfied: requests in /home/ak/anaconda3/lib/python3.9/site-packages (from torchvision->groundingdino==0.1.0) (2.27.1)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /home/ak/anaconda3/lib/python3.9/site-packages (from torchvision->groundingdino==0.1.0) (9.5.0)
Requirement already satisfied: packaging>=20.0 in /home/ak/anaconda3/lib/python3.9/site-packages (from transformers->groundingdino==0.1.0) (21.3)
Requirement already satisfied: regex!=2019.12.17 in /home/ak/anaconda3/lib/python3.9/site-packages (from transformers->groundingdino==0.1.0) (2022.3.15)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in /home/ak/anaconda3/lib/python3.9/site-packages (from transformers->groundingdino==0.1.0) (0.13.3)
Requirement already satisfied: tqdm>=4.27 in /home/ak/anaconda3/lib/python3.9/site-packages (from transformers->groundingdino==0.1.0) (4.64.0)
Requirement already satisfied: fsspec in /home/ak/anaconda3/lib/python3.9/site-packages (from huggingface-hub->timm->groundingdino==0.1.0) (2022.2.0)
Requirement already satisfied: contourpy>=1.0.1 in /home/ak/anaconda3/lib/python3.9/site-packages (from matplotlib>=2.1.0->pycocotools->groundingdino==0.1.0) (1.1.1)
Requirement already satisfied: cycler>=0.10 in /home/ak/anaconda3/lib/python3.9/site-packages (from matplotlib>=2.1.0->pycocotools->groundingdino==0.1.0) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /home/ak/anaconda3/lib/python3.9/site-packages (from matplotlib>=2.1.0->pycocotools->groundingdino==0.1.0) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/ak/anaconda3/lib/python3.9/site-packages (from matplotlib>=2.1.0->pycocotools->groundingdino==0.1.0) (1.3.2)
Requirement already satisfied: pyparsing>=2.3.1 in /home/ak/anaconda3/lib/python3.9/site-packages (from matplotlib>=2.1.0->pycocotools->groundingdino==0.1.0) (3.0.4)
Requirement already satisfied: python-dateutil>=2.7 in /home/ak/anaconda3/lib/python3.9/site-packages (from matplotlib>=2.1.0->pycocotools->groundingdino==0.1.0) (2.8.2)
Requirement already satisfied: importlib-resources>=3.2.0 in /home/ak/anaconda3/lib/python3.9/site-packages (from matplotlib>=2.1.0->pycocotools->groundingdino==0.1.0) (6.1.0)
Requirement already satisfied: MarkupSafe>=0.23 in /home/ak/anaconda3/lib/python3.9/site-packages (from jinja2->torch->groundingdino==0.1.0) (2.0.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/ak/anaconda3/lib/python3.9/site-packages (from requests->torchvision->groundingdino==0.1.0) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in /home/ak/anaconda3/lib/python3.9/site-packages (from requests->torchvision->groundingdino==0.1.0) (2021.10.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in /home/ak/anaconda3/lib/python3.9/site-packages (from requests->torchvision->groundingdino==0.1.0) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /home/ak/anaconda3/lib/python3.9/site-packages (from requests->torchvision->groundingdino==0.1.0) (3.3)
Requirement already satisfied: mpmath>=0.19 in /home/ak/anaconda3/lib/python3.9/site-packages (from sympy->torch->groundingdino==0.1.0) (1.2.1)
Requirement already satisfied: zipp>=3.1.0 in /home/ak/anaconda3/lib/python3.9/site-packages (from importlib-resources>=3.2.0->matplotlib>=2.1.0->pycocotools->groundingdino==0.1.0) (3.7.0)
Requirement already satisfied: six>=1.5 in /home/ak/anaconda3/lib/python3.9/site-packages (from python-dateutil>=2.7->matplotlib>=2.1.0->pycocotools->groundingdino==0.1.0) (1.16.0)
DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
Installing collected packages: groundingdino
  Running setup.py develop for groundingdino
    error: subprocess-exited-with-error
    
    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> [59 lines of output]
        Building wheel groundingdino-0.1.0
        Compiling with CUDA
        running develop
        /home/ak/anaconda3/lib/python3.9/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
          warnings.warn(
        /home/ak/anaconda3/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
          warnings.warn(
        running egg_info
        writing groundingdino.egg-info/PKG-INFO
        writing dependency_links to groundingdino.egg-info/dependency_links.txt
        writing requirements to groundingdino.egg-info/requires.txt
        writing top-level names to groundingdino.egg-info/top_level.txt
        /home/ak/anaconda3/lib/python3.9/site-packages/torch/utils/cpp_extension.py:476: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
          warnings.warn(msg.format('we could not find ninja.'))
        reading manifest file 'groundingdino.egg-info/SOURCES.txt'
        adding license file 'LICENSE'
        writing manifest file 'groundingdino.egg-info/SOURCES.txt'
        running build_ext
        Traceback (most recent call last):
          File "<string>", line 2, in <module>
          File "<pip-setuptools-caller>", line 34, in <module>
          File "/media/ak/HD/DEVA/Grounded-Segment-Anything/Grounded-Segment-Anything/GroundingDINO/setup.py", line 200, in <module>
            setup(
          File "/home/ak/anaconda3/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
            return distutils.core.setup(**attrs)
          File "/home/ak/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 148, in setup
            return run_commands(dist)
          File "/home/ak/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
            dist.run_commands()
          File "/home/ak/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
            self.run_command(cmd)
          File "/home/ak/anaconda3/lib/python3.9/site-packages/setuptools/dist.py", line 1214, in run_command
            super().run_command(command)
          File "/home/ak/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
            cmd_obj.run()
          File "/home/ak/anaconda3/lib/python3.9/site-packages/setuptools/command/develop.py", line 34, in run
            self.install_for_development()
          File "/home/ak/anaconda3/lib/python3.9/site-packages/setuptools/command/develop.py", line 114, in install_for_development
            self.run_command('build_ext')
          File "/home/ak/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
            self.distribution.run_command(command)
          File "/home/ak/anaconda3/lib/python3.9/site-packages/setuptools/dist.py", line 1214, in run_command
            super().run_command(command)
          File "/home/ak/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
            cmd_obj.run()
          File "/home/ak/anaconda3/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 79, in run
            _build_ext.run(self)
          File "/home/ak/anaconda3/lib/python3.9/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
            _build_ext.build_ext.run(self)
          File "/home/ak/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
            self.build_extensions()
          File "/home/ak/anaconda3/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 499, in build_extensions
            _check_cuda_version(compiler_name, compiler_version)
          File "/home/ak/anaconda3/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 387, in _check_cuda_version
            raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
        RuntimeError:
        The detected CUDA version (12.2) mismatches the version that was used to compile
        PyTorch (11.8). Please make sure to use the same CUDA versions.
        
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> [59 lines of output]
    Building wheel groundingdino-0.1.0
    Compiling with CUDA
    running develop
    /home/ak/anaconda3/lib/python3.9/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    /home/ak/anaconda3/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    running egg_info
    writing groundingdino.egg-info/PKG-INFO
    writing dependency_links to groundingdino.egg-info/dependency_links.txt
    writing requirements to groundingdino.egg-info/requires.txt
    writing top-level names to groundingdino.egg-info/top_level.txt
    /home/ak/anaconda3/lib/python3.9/site-packages/torch/utils/cpp_extension.py:476: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
      warnings.warn(msg.format('we could not find ninja.'))
    reading manifest file 'groundingdino.egg-info/SOURCES.txt'
    adding license file 'LICENSE'
    writing manifest file 'groundingdino.egg-info/SOURCES.txt'
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 2, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "/media/ak/HD/DEVA/Grounded-Segment-Anything/Grounded-Segment-Anything/GroundingDINO/setup.py", line 200, in <module>
        setup(
      File "/home/ak/anaconda3/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
        return distutils.core.setup(**attrs)
      File "/home/ak/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 148, in setup
        return run_commands(dist)
      File "/home/ak/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
        dist.run_commands()
      File "/home/ak/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
        self.run_command(cmd)
      File "/home/ak/anaconda3/lib/python3.9/site-packages/setuptools/dist.py", line 1214, in run_command
        super().run_command(command)
      File "/home/ak/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
        cmd_obj.run()
      File "/home/ak/anaconda3/lib/python3.9/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/home/ak/anaconda3/lib/python3.9/site-packages/setuptools/command/develop.py", line 114, in install_for_development
        self.run_command('build_ext')
      File "/home/ak/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/ak/anaconda3/lib/python3.9/site-packages/setuptools/dist.py", line 1214, in run_command
        super().run_command(command)
      File "/home/ak/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
        cmd_obj.run()
      File "/home/ak/anaconda3/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/home/ak/anaconda3/lib/python3.9/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/home/ak/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/home/ak/anaconda3/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 499, in build_extensions
        _check_cuda_version(compiler_name, compiler_version)
      File "/home/ak/anaconda3/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 387, in _check_cuda_version
        raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
    RuntimeError:
    The detected CUDA version (12.2) mismatches the version that was used to compile
    PyTorch (11.8). Please make sure to use the same CUDA versions.
    
    [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.

```

```
nvidia-smi
Mon Sep 25 22:45:06 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4090        On  | 00000000:01:00.0  On |                  Off |
|  0%   44C    P8              25W / 450W |    321MiB / 24564MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1312      G   /usr/lib/xorg/Xorg                          112MiB |
|    0   N/A  N/A      1593      G   /usr/bin/gnome-shell                         32MiB |
|    0   N/A  N/A      3812      G   ...irefox/3131/usr/lib/firefox/firefox      158MiB |
+---------------------------------------------------------------------------------------+
```

**Comment by hkchengrex** [comment]
It seems like your PyTorch's CUDA does not match the CUDA version that you are trying to compile GroundingDINO with. The solution would be to use the same version.

**Comment by AK51** [comment]
Oh yes,
I fixed it with 
```
conda install -c "nvidia/label/cuda-11.7.0" cuda-toolkit
```
Cheers
