### ISSUE TITLE
RuntimeError: shape '[1, 63, 512, 20, 27]' is invalid for input of size 19353600

### ISSUE THREAD

**Issue by GuanghaoJin** [hkchengrex/Tracking-Anything-with-DEVA#97]
When I tried to run this model in my own dataset, I am always facing such problem.
Traceback (most recent call last):
  File "/home/Tracking-Anything-with-DEVA/demo/demo_automatic.py", line 64, in <module>
    process_frame(deva, sam_model, im_path, result_saver, ti, image_np=frame)
  File "/home/anaconda3/envs/VTimeLLM/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/Tracking-Anything-with-DEVA/deva/ext/automatic_processor.py", line 74, in process_frame_automatic
    _, mask, new_segments_info = deva.vote_in_temporary_buffer(
  File "/home/Tracking-Anything-with-DEVA/deva/inference/inference_core.py", line 122, in vote_in_temporary_buffer
    projected_ti, projected_mask, projected_info = find_consensus_auto_association(
  File "/home/Tracking-Anything-with-DEVA/deva/inference/consensus_automatic.py", line 165, in find_consensus_auto_association
    projected_mask = spatial_alignment(ti, image, mask, keyframe_ti, keyframe_image,
  File "/home/Tracking-Anything-with-DEVA/deva/inference/consensus_associated.py", line 59, in spatial_alignment
    memory_readout = memory_readout.view(1, num_objects, config['value_dim'], h // 16, w // 16)
RuntimeError: shape '[1, 63, 512, 30, 40]' is invalid for input of size 43545600.
Could you tell me how to fix this error?

**Comment by hkchengrex** [comment]
You mentioned that this happens when you test on your own dataset, so I suppose it does not occur with our data? One possibility is that the input frames are not of a consistent size.

**Comment by hkchengrex** [comment]
Please feel free to re-open if there are any updates.
